source 'https://rubygems.org'
ruby '2.1.3'
gem 'rails', '4.1.6'
gem 'sass-rails', '>= 3.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'modernizr-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'cancan'
gem 'figaro'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'rolify'
gem 'simple_form'
gem 'slim'
gem 'acts-as-taggable-on'
gem 'friendly_id'
gem 'websocket-rails'
gem 'redis-rails'
gem 'resque', '~> 2.0.0.pre.1', github: 'resque/resque'
gem 'geocoder'
gem 'breadcrumbs_on_rails'
gem 'ember-rails'
gem 'ember-source', '1.8.0'
gem 'casein', '5.0.0'

group :development do gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'haml-rails'
  gem 'haml2slim'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'pry'
  gem 'capistrano', '~> 3.2.0'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano-rails', '~> 1.1.1'
  gem 'capistrano-rbenv', github: "capistrano/rbenv"
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'sqlite3'
end
group :production do
  gem 'thin'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end
