source 'https://rubygems.org'
ruby '2.1.5'
gem 'rails', '4.1.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'modernizr-rails'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'sass-rails', '>= 3.2'
gem 'cancan'
gem 'figaro'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'rolify'
gem 'simple_form'
gem 'slim'
gem 'acts-as-taggable-on'
gem 'friendly_id'
gem 'websocket-rails', github: 'depili/websocket-rails'
gem 'redis', :require => ["redis", "redis/connection/hiredis"]
gem 'resque', '~> 2.0.0.pre.1', github: 'resque/resque'
gem 'geocoder'
gem 'breadcrumbs_on_rails'
gem 'ember-rails'
gem 'ember-source', '1.8.0'
gem 'therubyracer'
gem 'nav_lynx'
gem 'mercury-rails', github: 'jejacks0n/mercury'
gem 'font-awesome-rails'
gem 'owlcarousel-rails'

group :development do
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-spring'
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'haml-rails'
  gem 'haml2slim'
  gem 'html2haml'
  gem 'rails_layout'
  gem 'pry'
  gem 'capistrano', '~> 3.2.0'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano-rails', '~> 1.1.1'
  gem 'capistrano-rbenv', github: "capistrano/rbenv"
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'sqlite3'
end
group :production do
  gem 'thin'
  gem 'pg'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end
gem 'paperclip'